const ROOT = 'results/genres';

export const FETCH_GENRES_REQUEST = `${ROOT}/FETCH_GENRES_REQUEST`;
export const FETCH_GENRES_FAILURE = `${ROOT}/FETCH_GENRES_FAILURE`;
export const FETCH_GENRES_SUCCESS = `${ROOT}/FETCH_GENRES_SUCCESS`;
export const SHOW_MOVIES_BY_FILTER = `${ROOT}/SHOW_MOVIES_BY_FILTER`;
export const HIDE_MOVIES_BY_FILTER = `${ROOT}/HIDE_MOVIES_BY_FILTER`;
